### ISSUE TITLE
setEventValue removed

### ISSUE THREAD

**Issue by DHosseiny** [adtrace/adtrace_sdk_android#2]
We used this code for sending events in v1.0.3:
```
val adTraceEvent = AdTraceSdkEvent(getAdTraceEventToken(localAdTraceEvent.type))
adTraceEvent.setEventValue(localAdTraceEvent.value)
AdTrace.trackEvent(adTraceEvent)
```
But now in v2.0.2 there is no setEventValue function.
I can't find any changelog about it in releases.
How to migrate to 2.0.2 with the same functionality?

**Comment by namini40** [comment]
check [this link](https://github.com/adtrace/adtrace_sdk_android#event-parameters-1) . now you can add `key` - `value` pairs as many as you want.

thanks for feedback, this will be considered!

**Comment by DHosseiny** [comment]
There is no `addEventParameter`(2.3.0) in the new version. What is the replacement method? @namini40

**Comment by namini40** [comment]
as you may want to check [our last version of `AdTraceEvent`](https://github.com/adtrace/adtrace_sdk_android/blob/3757b9366cc98788349412553adfde9e85e753b1/android-sdk/src/main/java/io/adtrace/sdk/AdTraceEvent.java#L52) (`android-sdk:2.4.0`) contains `addEventParameter`. 

[the previous version for `AdTraceEvent`](https://github.com/adtrace/adtrace_sdk_android/blob/719381ff450b86b39acff8b34f653ac6775eb15d/android-sdk/src/main/java/io/adtrace/sdk/AdTraceEvent.java#L53) (`android-sdk:2.3.0`) also has this method.

[Release Assets](https://github.com/adtrace/adtrace_sdk_android/releases/tag/v2.3.0) (`.jar` and `.aar` files) are tested too with same result. 

What I understood from your question is you could not find the method or maybe a problem with the library from "maven" repository that did not load it properly.
please let me know if there is some way to reproduce the issue so that we could solve the problem together.
thank you @DHosseiny

**Comment by DHosseiny** [comment]
Yes it was my IDE issue. thanks
